"""Compile validated, approved data into a fixed, reviewable runtime."""
import ast
import hashlib
import io
import json
import zipfile
from pathlib import Path
from app.models.application import ApplicationSpec
from app.templates.application.schema_contract import compatibility
from app.services.application_assets import assets
from app.services.application_locale import localize

TEMPLATE = Path(__file__).resolve().parents[1] / 'templates' / 'application'


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(',', ':')).encode()).hexdigest()


def compile_application(spec, build_id):
    spec = ApplicationSpec.model_validate(spec).model_dump()
    files = {str(p.relative_to(TEMPLATE)).replace('\\', '/'): p.read_text(encoding='utf-8')
             for p in TEMPLATE.rglob('*') if p.is_file() and '__pycache__' not in p.parts}
    files['spec.json'] = json.dumps(spec, ensure_ascii=False, indent=2)
    files['release.json'] = json.dumps({'build_id': build_id, 'spec_hash': digest(spec)})
    files.update(assets(spec, build_id))
    files['public/style.css'] += '\nbutton:hover{border-color:' + spec['accent'] + '}\n'
    localize(files, spec)
    files['Dockerfile'] = ('FROM python:3.13-slim\nWORKDIR /app\nCOPY . /app\n'
                           'RUN mkdir -p /app/data && chown -R 10001:10001 /app\n'
                           'USER 10001:10001\nENV PORT=8080 DATABASE_PATH=/app/data/application.db PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1\n'
                           'EXPOSE 8080\nCMD ["python", "server.py"]\n')
    files['.dockerignore'] = 'data\n.env\n.git\n__pycache__\n*.db\n'
    files['.env.example'] = 'ADMIN_EMAIL=\nADMIN_PASSWORD=\nAPP_ORIGIN=https://your-service.onrender.com\nCOOKIE_SECURE=true\nDATABASE_PATH=/app/data/application.db\nPORT=8080\n'
    files['README.md'] = f'''# {spec['name']}

Generated by shift.AI from an explicitly approved application specification.

Requires Python 3.13; no third-party runtime packages. Set ADMIN_EMAIL and
ADMIN_PASSWORD (12+ characters) in the process environment before first startup.
Set APP_ORIGIN to the exact public HTTPS origin; serve behind a TLS reverse proxy.
Run `python server.py`. For local use only, set COOKIE_SECURE=false and
APP_ORIGIN=http://localhost:8080. Environment files are examples, not auto-loaded.

The administrator creates team accounts in the application. Public signup is disabled.
Database: SQLite on a persistent disk at DATABASE_PATH. Keep one service instance.
Never use an ephemeral filesystem for production. Back up the disk independently.
On a new application release the runtime saves a consistent SQLite backup before
applying additive schema changes. Old tables/columns and business records are retained.
Restoring code does not undo data edits; restore database backups as a separate,
operator-reviewed action. Do not scale horizontally with this SQLite runtime.

Render: deploy this Docker image to an image-backed web service with a persistent
disk mounted at /app/data (writable by UID 10001), PORT=8080, COOKIE_SECURE=true,
APP_ORIGIN, ADMIN_EMAIL and ADMIN_PASSWORD as secret service environment values.
Health check: /health. Never put passwords in the image or source repository.

`python -m unittest selftest -v` runs isolated auth, roles, CRUD, relation,
workflow and persistence contract checks. The platform records separately whether
these tests actually ran. Requirements marked manual are NOT implemented.

Known runtime scope: relational CRUD, forms, search, roles, finite-state transitions.
No arbitrary integration adapters, custom business algorithms, billing, email, or
native mobile binaries are generated. See spec.json for assumptions and limitations.
'''
    findings = []
    for requirement in spec['requirements']:
        if requirement['implementation'] == 'manual':
            findings.append({'severity': 'high', 'component': requirement['id'], 'issue': requirement['description'],
                             'evidence': 'Requirement is marked manual in the approved specification.',
                             'correction': 'Implement and validate the required adapter or custom workflow.', 'status': 'open'})
    for path, content in files.items():
        if path.endswith('.py'):
            ast.parse(content, filename=path)
    manifest = {path: hashlib.sha256(content.encode()).hexdigest() for path, content in files.items()}
    return files, manifest, findings


def archive(files):
    output = io.BytesIO()
    with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as bundle:
        for path, content in files.items():
            bundle.writestr(path, content)
    return output.getvalue()
