var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/project/[id]/[[...section]]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1gvktgm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1kpskn9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/_0gmf19d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_project_[id]_[[___section]]_page_actions_1962ud-.js")
R.m(97608)
module.exports=R.m(97608).exports
